class LocationModel {
  final String id;
  final String name;
  final String address;
  final String category;
  final int queueCount;
  final int waitTimeMinutes;
  final String status; // 'empty' | 'moderate' | 'busy'
  final double rating;
  final String icon;

  LocationModel({
    required this.id,
    required this.name,
    required this.address,
    required this.category,
    required this.queueCount,
    required this.waitTimeMinutes,
    required this.status,
    required this.rating,
    required this.icon,
  });

  // সুপাবেস ডাটাবেজ (Map/JSON) থেকে নিখুঁতভাবে ডেটা কনভার্ট করার মেথড
  factory LocationModel.fromJson(Map<String, dynamic> json) {
    return LocationModel(
      id: json['id']?.toString() ?? '',
      name: json['name'] ?? '',
      address: json['address'] ?? '',
      category: json['category'] ?? '',

      // ডাটাবেজের কলাম int না হয়ে অনেক সময় string আসতে পারে, তাই safely পার্স করা হলো
      queueCount:
          int.tryParse(json['queue_count']?.toString() ?? '') ??
          int.tryParse(json['queueCount']?.toString() ?? '') ??
          0,

      waitTimeMinutes:
          int.tryParse(json['wait_time_minutes']?.toString() ?? '') ??
          int.tryParse(json['estimated_wait_time']?.toString() ?? '') ??
          int.tryParse(json['waitTimeMinutes']?.toString() ?? '') ??
          0,

      status: json['status'] ?? json['queue_status'] ?? 'empty',

      // রেটিং int বা double যাই আসুক safely ডাবল-এ কনভার্ট হবে
      rating: double.tryParse(json['rating']?.toString() ?? '') ?? 0.0,
      icon: json['icon'] ?? '🏢',
    );
  }
}

// ৩০টি নতুন লোকেশনসহ আপডেটেড মক ডেটা লিস্ট (Healthcare, Banking, Government)
final List<LocationModel> mockLocations = [
  // ==================== HEALTHCARE (১০টি লোকেশন) ====================
  LocationModel(
    id: 'h1',
    name: 'Dhaka Medical College Hospital',
    address: 'Ramna, Dhaka',
    category: 'Healthcare',
    queueCount: 45,
    waitTimeMinutes: 90,
    status: 'busy',
    rating: 4.0,
    icon: '🏥',
  ),
  LocationModel(
    id: 'h2',
    name: 'Square Hospital',
    address: 'Panthapath, Dhaka',
    category: 'Healthcare',
    queueCount: 12,
    waitTimeMinutes: 20,
    status: 'empty',
    rating: 4.6,
    icon: '🏥',
  ),
  LocationModel(
    id: 'h3',
    name: 'Evercare Hospital',
    address: 'Bashundhara R/A, Dhaka',
    category: 'Healthcare',
    queueCount: 18,
    waitTimeMinutes: 35,
    status: 'moderate',
    rating: 4.5,
    icon: '🏥',
  ),
  LocationModel(
    id: 'h4',
    name: 'Labaid Specialized Hospital',
    address: 'Dhanmondi, Dhaka',
    category: 'Healthcare',
    queueCount: 25,
    waitTimeMinutes: 45,
    status: 'busy',
    rating: 4.2,
    icon: '🏥',
  ),
  LocationModel(
    id: 'h5',
    name: 'Birdem General Hospital',
    address: 'Shahbagh, Dhaka',
    category: 'Healthcare',
    queueCount: 30,
    waitTimeMinutes: 60,
    status: 'busy',
    rating: 4.1,
    icon: '🏥',
  ),
  LocationModel(
    id: 'h6',
    name: 'National Heart Foundation',
    address: 'Mirpur, Dhaka',
    category: 'Healthcare',
    queueCount: 22,
    waitTimeMinutes: 40,
    status: 'moderate',
    rating: 4.3,
    icon: '🏥',
  ),
  LocationModel(
    id: 'h7',
    name: 'United Hospital',
    address: 'Gulshan, Dhaka',
    category: 'Healthcare',
    queueCount: 8,
    waitTimeMinutes: 15,
    status: 'empty',
    rating: 4.7,
    icon: '🏥',
  ),
  LocationModel(
    id: 'h8',
    name: 'Ibn Sina Specialized Hospital',
    address: 'Kalyanpur, Dhaka',
    category: 'Healthcare',
    queueCount: 15,
    waitTimeMinutes: 30,
    status: 'moderate',
    rating: 4.4,
    icon: '🏥',
  ),
  LocationModel(
    id: 'h9',
    name: 'Kurmitola General Hospital',
    address: 'Airport Road, Dhaka',
    category: 'Healthcare',
    queueCount: 35,
    waitTimeMinutes: 70,
    status: 'busy',
    rating: 3.9,
    icon: '🏥',
  ),
  LocationModel(
    id: 'h10',
    name: 'Shaheed Suhrawardy Hospital',
    address: 'Sher-e-Bangla Nagar, Dhaka',
    category: 'Healthcare',
    queueCount: 40,
    waitTimeMinutes: 80,
    status: 'busy',
    rating: 3.8,
    icon: '🏥',
  ),

  // ==================== BANKING (১০টি লোকেশন) ====================
  LocationModel(
    id: 'b1',
    name: 'Sonali Bank - Principal Branch',
    address: 'Motijheel, Dhaka',
    category: 'Banking',
    queueCount: 50,
    waitTimeMinutes: 100,
    status: 'busy',
    rating: 3.5,
    icon: '🏦',
  ),
  LocationModel(
    id: 'b2',
    name: 'Islami Bank Bangladesh Ltd',
    address: 'Mirpur-10, Dhaka',
    category: 'Banking',
    queueCount: 28,
    waitTimeMinutes: 55,
    status: 'busy',
    rating: 4.1,
    icon: '🏦',
  ),
  LocationModel(
    id: 'b3',
    name: 'BRAC Bank Assemi Branch',
    address: 'Uttara, Dhaka',
    category: 'Banking',
    queueCount: 14,
    waitTimeMinutes: 25,
    status: 'empty',
    rating: 4.3,
    icon: '🏦',
  ),
  LocationModel(
    id: 'b4',
    name: 'Dutch-Bangla Bank Fast Track',
    address: 'Dhanmondi, Dhaka',
    category: 'Banking',
    queueCount: 19,
    waitTimeMinutes: 35,
    status: 'moderate',
    rating: 3.9,
    icon: '🏦',
  ),
  LocationModel(
    id: 'b5',
    name: 'City Bank VIP Lounge',
    address: 'Gulshan, Dhaka',
    category: 'Banking',
    queueCount: 5,
    waitTimeMinutes: 10,
    status: 'empty',
    rating: 4.7,
    icon: '🏦',
  ),
  LocationModel(
    id: 'b6',
    name: 'Mutual Trust Bank',
    address: 'Banani, Dhaka',
    category: 'Banking',
    queueCount: 9,
    waitTimeMinutes: 15,
    status: 'empty',
    rating: 4.2,
    icon: '🏦',
  ),
  LocationModel(
    id: 'b7',
    name: 'Eastern Bank Ltd (EBL)',
    address: 'Karwan Bazar, Dhaka',
    category: 'Banking',
    queueCount: 11,
    waitTimeMinutes: 20,
    status: 'empty',
    rating: 4.4,
    icon: '🏦',
  ),
  LocationModel(
    id: 'b8',
    name: 'Standard Chartered Bank',
    address: 'Nasirabad, Chattogram',
    category: 'Banking',
    queueCount: 7,
    waitTimeMinutes: 15,
    status: 'empty',
    rating: 4.6,
    icon: '🏦',
  ),
  LocationModel(
    id: 'b9',
    name: 'Bank Asia Main Branch',
    address: 'Agrabad, Chattogram',
    category: 'Banking',
    queueCount: 16,
    waitTimeMinutes: 30,
    status: 'moderate',
    rating: 4.0,
    icon: '🏦',
  ),
  LocationModel(
    id: 'b10',
    name: 'Prime Bank Limited',
    address: 'Khulna Branch, Khulna',
    category: 'Banking',
    queueCount: 13,
    waitTimeMinutes: 25,
    status: 'empty',
    rating: 4.1,
    icon: '🏦',
  ),

  // ==================== GOVERNMENT (১০টি লোকেশন) ====================
  LocationModel(
    id: 'g1',
    name: 'Regional Passport Office',
    address: 'Agargaon, Dhaka',
    category: 'Government',
    queueCount: 120,
    waitTimeMinutes: 240,
    status: 'busy',
    rating: 2.9,
    icon: '🏛️',
  ),
  LocationModel(
    id: 'g2',
    name: 'BRTA Mirpur Office',
    address: 'Mirpur-13, Dhaka',
    category: 'Government',
    queueCount: 95,
    waitTimeMinutes: 180,
    status: 'busy',
    rating: 3.1,
    icon: '🏛️',
  ),
  LocationModel(
    id: 'g3',
    name: 'Election Commission Office',
    address: 'Agargaon, Dhaka',
    category: 'Government',
    queueCount: 40,
    waitTimeMinutes: 75,
    status: 'busy',
    rating: 3.5,
    icon: '🏛️',
  ),
  LocationModel(
    id: 'g4',
    name: 'Dhaka South City Corporation',
    address: 'Nagar Bhaban, Fulbaria',
    category: 'Government',
    queueCount: 25,
    waitTimeMinutes: 50,
    status: 'moderate',
    rating: 3.6,
    icon: '🏛️',
  ),
  LocationModel(
    id: 'g5',
    name: 'National ID (NID) Wing',
    address: 'Agargaon, Dhaka',
    category: 'Government',
    queueCount: 65,
    waitTimeMinutes: 120,
    status: 'busy',
    rating: 3.2,
    icon: '🏛️',
  ),
  LocationModel(
    id: 'g6',
    name: 'Sub-Registry Office',
    address: 'Gulshan, Dhaka',
    category: 'Government',
    queueCount: 35,
    waitTimeMinutes: 60,
    status: 'busy',
    rating: 3.4,
    icon: '🏛️',
  ),
  LocationModel(
    id: 'g7',
    name: 'DESCO Customer Service',
    address: 'Uttara, Dhaka',
    category: 'Government',
    queueCount: 18,
    waitTimeMinutes: 30,
    status: 'moderate',
    rating: 4.0,
    icon: '🏛️',
  ),
  LocationModel(
    id: 'g8',
    name: 'Titas Gas Head Office',
    address: 'Karwan Bazar, Dhaka',
    category: 'Government',
    queueCount: 22,
    waitTimeMinutes: 45,
    status: 'moderate',
    rating: 3.7,
    icon: '🏛️',
  ),
  LocationModel(
    id: 'g9',
    name: 'Custom House',
    address: 'Airport Road, Dhaka',
    category: 'Government',
    queueCount: 30,
    waitTimeMinutes: 55,
    status: 'busy',
    rating: 3.5,
    icon: '🏛️',
  ),
  LocationModel(
    id: 'g10',
    name: 'Post Office (GPO)',
    address: 'Zero Point, Gulistan',
    category: 'Government',
    queueCount: 15,
    waitTimeMinutes: 25,
    status: 'empty',
    rating: 3.9,
    icon: '🏛️',
  ),
];
