// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCzA7yqX6RyQL8489HC1RxQdW6b1gQP1k',
    appId: '1:109411648100:web:087b630e65e6b4d6d49571',
    messagingSenderId: '109411648100',
    projectId: 'queueless-app-3c634',
    authDomain: 'queueless-app-3c634.firebaseapp.com',
    storageBucket: 'queueless-app-3c634.firebasestorage.app',
    measurementId: 'G-CDKXM93M51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5sTAYzETQos3ozhVIvB4FxhgsMGEFFOA',
    appId: '1:109411648100:android:c41caf0dad0743abd49571',
    messagingSenderId: '109411648100',
    projectId: 'queueless-app-3c634',
    storageBucket: 'queueless-app-3c634.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf-lDZF_r4B6UWvKer_X6c5DvovvmXx98',
    appId: '1:109411648100:ios:430904c120235dded49571',
    messagingSenderId: '109411648100',
    projectId: 'queueless-app-3c634',
    storageBucket: 'queueless-app-3c634.firebasestorage.app',
    iosBundleId: 'com.example.queueless',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf-lDZF_r4B6UWvKer_X6c5DvovvmXx98',
    appId: '1:109411648100:ios:430904c120235dded49571',
    messagingSenderId: '109411648100',
    projectId: 'queueless-app-3c634',
    storageBucket: 'queueless-app-3c634.firebasestorage.app',
    iosBundleId: 'com.example.queueless',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCzA7yqX6RyQL8489HC1RxQdW6b1gQP1k',
    appId: '1:109411648100:web:41635a9c479038b1d49571',
    messagingSenderId: '109411648100',
    projectId: 'queueless-app-3c634',
    authDomain: 'queueless-app-3c634.firebaseapp.com',
    storageBucket: 'queueless-app-3c634.firebasestorage.app',
    measurementId: 'G-SP68PBQPT5',
  );
}
